spring:
#  config:
#    import: optional:secrets.properties
  datasource:
    username: ${USERNAME}
    password: ${PASSWORD}
    url: jdbc:mysql://localhost:3306/vote_management

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect


        logging:
        level:
        org.springframework.security: DEBUG

